/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:31:25Z</remarks>
using System.Text.Json;

namespace SpocR.Samples.WebApi.DataContext.TableTypes
{
    public interface ITableType
    {
    }
}
