/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 16:15:37Z</remarks>
using System.Text.Json;

namespace spocr.DataContext.TableTypes
{
    public interface ITableType
    {
    }
}
