/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-12 23:41:04Z</remarks>
using System;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using System.Threading;
using System.Threading.Tasks;
using SpocR.Samples.Mssql.DataContext.Models;
using SpocR.Samples.Mssql.DataContext.Outputs;
using SpocR.Samples.Mssql.DataContext.Models.Samples;
using SpocR.Samples.Mssql.DataContext.Inputs.Samples;
using SpocR.Samples.Mssql.DataContext.TableTypes.Samples;

namespace SpocR.Samples.Mssql.DataContext.StoredProcedures.Samples
{
    public static class UserContactSyncExtensions
    {
        public static Task<UserContactSync> UserContactSyncAsync(this IAppDbContextPipe context, UserContactSyncInput input, CancellationToken cancellationToken)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            var parameters = new List<SqlParameter>
            {
                AppDbContext.GetCollectionParameter("Contacts", input.Contacts)
            };
            return context.ExecuteSingleAsync<UserContactSync>("[samples].[UserContactSync]", parameters, cancellationToken);
        }

        public static Task<UserContactSync> UserContactSyncAsync(this IAppDbContext context, UserContactSyncInput input, CancellationToken cancellationToken)
        {
            return context.CreatePipe().UserContactSyncAsync(input, cancellationToken);
        }
    }
}