/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-13 09:48:54Z</remarks>
using System;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using System.Threading;
using System.Threading.Tasks;
using SpocR.Samples.Mssql.DataContext.Models;
using SpocR.Samples.Mssql.DataContext.Outputs;
using SpocR.Samples.Mssql.DataContext.Models.Samples;
using SpocR.Samples.Mssql.DataContext.Inputs.Samples;

namespace SpocR.Samples.Mssql.DataContext.StoredProcedures.Samples
{
    public static class UserFindExtensions
    {
        public static Task<UserFind> UserFindAsync(this IAppDbContextPipe context, UserFindInput input, CancellationToken cancellationToken)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            var parameters = new List<SqlParameter>
            {
                AppDbContext.GetParameter("UserId", input.UserId, false, 4)
            };
            return context.ExecuteSingleAsync<UserFind>("[samples].[UserFind]", parameters, cancellationToken);
        }

        public static Task<UserFind> UserFindAsync(this IAppDbContext context, UserFindInput input, CancellationToken cancellationToken)
        {
            return context.CreatePipe().UserFindAsync(input, cancellationToken);
        }
    }
}