/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-12 23:41:04Z</remarks>
using System;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using System.Threading;
using System.Threading.Tasks;
using SpocR.Samples.Mssql.DataContext.Models;
using SpocR.Samples.Mssql.DataContext.Outputs;
using SpocR.Samples.Mssql.DataContext.Models.Samples;
using SpocR.Samples.Mssql.DataContext.Inputs.Samples;

namespace SpocR.Samples.Mssql.DataContext.StoredProcedures.Samples
{
    public static class UserDetailsWithOrdersExtensions
    {
        public static Task<UserDetailsWithOrders> UserDetailsWithOrdersAsync(this IAppDbContextPipe context, UserDetailsWithOrdersInput input, CancellationToken cancellationToken)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            var parameters = new List<SqlParameter>
            {
                AppDbContext.GetParameter("UserId", input.UserId, false, 4)
            };
            return context.ExecuteSingleAsync<UserDetailsWithOrders>("[samples].[UserDetailsWithOrders]", parameters, cancellationToken);
        }

        public static Task<UserDetailsWithOrders> UserDetailsWithOrdersAsync(this IAppDbContext context, UserDetailsWithOrdersInput input, CancellationToken cancellationToken)
        {
            return context.CreatePipe().UserDetailsWithOrdersAsync(input, cancellationToken);
        }
    }
}