/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:31:25Z</remarks>
using Microsoft.Extensions.DependencyInjection;
using System;

namespace SpocR.Samples.WebApi.DataContext;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddAppDbContext(this IServiceCollection services, Action<AppDbContextOptions> options = null)
    {
        if (options != null)
        {
            services.Configure(options);
        }

        services.AddScoped<IAppDbContext, AppDbContext>();
        return services;
    }
}
