/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:54:07Z</remarks>
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.Data.SqlClient;

namespace SpocR.Samples.WebApi.SpocR.Samples;

/// <summary>Auto-generated unified artifact for stored procedure [samples].[CreateUserWithOutput]. DO NOT EDIT.</summary>
public partial class SpocRDbContext
{
    
    // Input DTO (IN / INOUT parameters excluding OUTPUT-only)
    public readonly record struct CreateUserWithOutputInput(
        
        
        IEnumerable<string?> DisplayName,
        
        
        
        IEnumerable<string?> Email
        
        
    );
    

    
    // Output parameters DTO
    public class CreateUserWithOutputOutput
    {
        
        public int? UserId { get; set; }
        
    }
    

      { get; set; }
        
    }
    

    /// <summary>Executes stored procedure [samples].[CreateUserWithOutput]</summary>
    public async Task<CreateUserWithOutputOutput> CreateUserWithOutputAsync(CreateUserWithOutputInput input, Action<SpocRStoredProcedureCallOptions> configure = null, ISpocRTransaction transaction = null, CancellationToken cancellationToken = default)
    {
        var opts = new SpocRStoredProcedureCallOptions();
        configure?.Invoke(opts);
        var effectiveTx = transaction ?? opts.Transaction;
        
        var inputObj = new { DisplayName = input.DisplayName, Email = input.Email };
        
        var result = await ExecuteStoredProcedureAsync<object, CreateUserWithOutputOutput>("[samples].[CreateUserWithOutput]", inputObj, effectiveTx, opts.CommandTimeout, cancellationToken);
        return result;
    }
}
