/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:54:07Z</remarks>
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.Data.SqlClient;

namespace SpocR.Samples.WebApi.SpocR.Samples;

/// <summary>Auto-generated unified artifact for stored procedure [samples].[SumWithOutput]. DO NOT EDIT.</summary>
public partial class SpocRDbContext
{
    
    // Input DTO (IN / INOUT parameters excluding OUTPUT-only)
    public readonly record struct SumWithOutputInput(
        
        
        IEnumerable<int?> A,
        
        
        
        IEnumerable<int?> B
        
        
    );
    

    
    // Output parameters DTO
    public class SumWithOutputOutput
    {
        
        public int? Sum { get; set; }
        
        public bool? Success { get; set; }
        
    }
    

      { get; set; }
        
    }
    

    /// <summary>Executes stored procedure [samples].[SumWithOutput]</summary>
    public async Task<SumWithOutputOutput> SumWithOutputAsync(SumWithOutputInput input, Action<SpocRStoredProcedureCallOptions> configure = null, ISpocRTransaction transaction = null, CancellationToken cancellationToken = default)
    {
        var opts = new SpocRStoredProcedureCallOptions();
        configure?.Invoke(opts);
        var effectiveTx = transaction ?? opts.Transaction;
        
        var inputObj = new { A = input.A, B = input.B };
        
        var result = await ExecuteStoredProcedureAsync<object, SumWithOutputOutput>("[samples].[SumWithOutput]", inputObj, effectiveTx, opts.CommandTimeout, cancellationToken);
        return result;
    }
}
