/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:54:07Z</remarks>
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.Data.SqlClient;

namespace SpocR.Samples.WebApi.SpocR.Samples;

/// <summary>Auto-generated unified artifact for stored procedure [samples].[UserFind]. DO NOT EDIT.</summary>
public partial class SpocRDbContext
{
    
    // Input DTO (IN / INOUT parameters excluding OUTPUT-only)
    public readonly record struct UserFindInput(
        
        
        IEnumerable<int?> UserId
        
        
    );
    

      { get; set; }
        
    }
    

    
    // Result set model (tabular / JSON)
    public class UserFindResult
    {
        
        public int? UserId { get; set; }
        
        public string? Email { get; set; }
        
        public string? DisplayName { get; set; }
        
        public DateTime? CreatedAt { get; set; }
        
        public string? Bio { get; set; }
        
    }
    

    /// <summary>Executes stored procedure [samples].[UserFind]</summary>
    public async Task<UserFindResult> UserFindAsync(UserFindInput input, Action<SpocRStoredProcedureCallOptions> configure = null, ISpocRTransaction transaction = null, CancellationToken cancellationToken = default)
    {
        var opts = new SpocRStoredProcedureCallOptions();
        configure?.Invoke(opts);
        var effectiveTx = transaction ?? opts.Transaction;
        
        var inputObj = new { UserId = input.UserId };
        
        var result = await ExecuteStoredProcedureAsync<object, UserFindResult>("[samples].[UserFind]", inputObj, effectiveTx, opts.CommandTimeout, cancellationToken);
        return result;
    }
}
