/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:54:07Z</remarks>
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.Data.SqlClient;

namespace SpocR.Samples.WebApi.SpocR.Samples;

/// <summary>Auto-generated unified artifact for stored procedure [samples].[UserContactSync]. DO NOT EDIT.</summary>
public partial class SpocRDbContext
{
    
    // Input DTO (IN / INOUT parameters excluding OUTPUT-only)
    public readonly record struct UserContactSyncInput(
        
        
        IEnumerable<object> Contacts
        
        
    );
    

      { get; set; }
        
    }
    

    
    // Result set model (tabular / JSON)
    public class UserContactSyncResult
    {
        
        public int? UpdatedContacts { get; set; }
        
        public int? MissingContacts { get; set; }
        
    }
    

    /// <summary>Executes stored procedure [samples].[UserContactSync]</summary>
    public async Task<UserContactSyncResult> UserContactSyncAsync(UserContactSyncInput input, Action<SpocRStoredProcedureCallOptions> configure = null, ISpocRTransaction transaction = null, CancellationToken cancellationToken = default)
    {
        var opts = new SpocRStoredProcedureCallOptions();
        configure?.Invoke(opts);
        var effectiveTx = transaction ?? opts.Transaction;
        
        var inputObj = new { Contacts = input.Contacts };
        
        var result = await ExecuteStoredProcedureAsync<object, UserContactSyncResult>("[samples].[UserContactSync]", inputObj, effectiveTx, opts.CommandTimeout, cancellationToken);
        return result;
    }
}
