/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:54:07Z</remarks>
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.Data.SqlClient;

namespace SpocR.Samples.WebApi.SpocR.Samples;

/// <summary>Auto-generated unified artifact for stored procedure [samples].[UserOrderHierarchyJson]. DO NOT EDIT.</summary>
public partial class SpocRDbContext
{
    
         ,
        
        
    );
    

      { get; set; }
        
    }
    

    
    // Result set model (tabular / JSON)
    public class UserOrderHierarchyJsonResult
    {
        
        public int? UserId { get; set; }
        
        public string? DisplayName { get; set; }
        
        public string? Email { get; set; }
        
        public string? Orders { get; set; }
        
    }
    

    /// <summary>Executes stored procedure [samples].[UserOrderHierarchyJson]</summary>
    public async Task<UserOrderHierarchyJsonResult> UserOrderHierarchyJsonAsync(Action<SpocRStoredProcedureCallOptions> configure = null, ISpocRTransaction transaction = null, CancellationToken cancellationToken = default)
    {
        var opts = new SpocRStoredProcedureCallOptions();
        configure?.Invoke(opts);
        var effectiveTx = transaction ?? opts.Transaction;
        
        var inputObj = default(object);
        
        var result = await ExecuteStoredProcedureAsync<object, UserOrderHierarchyJsonResult>("[samples].[UserOrderHierarchyJson]", default, effectiveTx, opts.CommandTimeout, cancellationToken);
        return result;
    }
}
