/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 20:00:15Z</remarks>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SpocR.Samples.WebApi.DataContext.Inputs.Samples
{
    public class CreateUserWithOutputInput
    {
        public CreateUserWithOutputInput(string displayName, string email)
        {
            DisplayName = displayName;
            Email = email;
        }

        [StringLength(128)]
        public string DisplayName { get; set; }
        [StringLength(256)]
        public string Email { get; set; }
    }
}
