/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 22:44:50Z</remarks>
using System.ComponentModel.DataAnnotations;

namespace SpocR.Samples.WebApi.DataContext.Inputs.Samples;

public record CreateUserWithOutputInput(
    [property: MaxLength(128)] string DisplayName,
    [property: MaxLength(256)] string Email
);
