/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-09 11:53:55Z</remarks>
namespace SpocR.Samples.WebApi.DataContext.Inputs.Samples;

public record SumWithOutputInput(
    int? A,
    int? B
);
