/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 20:00:15Z</remarks>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SpocR.Samples.WebApi.DataContext.Inputs.Samples
{
    public class SumWithOutputInput
    {
        public SumWithOutputInput(int? a, int? b)
        {
            A = a;
            B = b;
        }

        public int? A { get; set; }
        public int? B { get; set; }
    }
}
