/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 21:06:45Z</remarks>
namespace SpocR.Samples.WebApi.DataContext.DataContext.Inputs.Samples;
public class UserFindInput
{ // modern stub
    public UserFindInput(int? userId)
    {
        UserId = userId;
    }

    public int? UserId { get; set; }
// TODO: Replace with modern template content
}