/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-09 14:08:34Z</remarks>
using System.ComponentModel.DataAnnotations;

namespace SpocR.Samples.WebApi.DataContext.Inputs.Samples;

public record UserBioUpdateInput(
    int? UserId,
    [property: StringLength(512)] string Bio
);
