/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 21:06:45Z</remarks>
using SpocR.Samples.WebApi.DataContext.DataContext.TableTypes.Samples;

namespace SpocR.Samples.WebApi.DataContext.DataContext.Inputs.Samples;
public class UserContactSyncInput
{ // modern stub
    public UserContactSyncInput(UserContactTableType contacts)
    {
        Contacts = contacts;
    }

    public UserContactTableType Contacts { get; set; }
// TODO: Replace with modern template content
}