/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 22:44:50Z</remarks>
using SpocR.Samples.WebApi.DataContext.DataContext.TableTypes.Samples;

namespace SpocR.Samples.WebApi.DataContext.Inputs.Samples;

public record UserContactSyncInput(
    UserContactTableType Contacts
);
