/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-14 14:39:27Z</remarks>
/// <summary>Generated interface for the database context abstraction.</summary>
namespace RestApi.SpocR;

using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;

public interface ISpocRDbContext
{
    /// <summary>Create and open a new connection (synchronous).</summary>
    DbConnection OpenConnection();
    /// <summary>Create and open a new connection asynchronously.</summary>
    Task<DbConnection> OpenConnectionAsync(CancellationToken cancellationToken = default);
    /// <summary>Simple health probe (true = can open & close a connection).</summary>
    Task<bool> HealthCheckAsync(CancellationToken cancellationToken = default);
    /// <summary>Configured command timeout in seconds (never &lt; 1).</summary>
    int CommandTimeoutSeconds { get; }
}
