/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Namespace corrected to include .SpocR suffix.</remarks>
namespace RestApi.SpocR;

public interface ITableType { }
