/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-14 11:54:01Z</remarks>
namespace RestApi.SpocR;

using System.Text.Json;

public sealed class SpocRDbContextOptions
{
    public string? ConnectionString { get; set; }
    /// <summary>Optional logical name (IConfiguration.GetConnectionString) – defaults to "DefaultConnection".</summary>
    public string? ConnectionStringName { get; set; }
    public int? CommandTimeoutSeconds { get; set; }
    /// <summary>Max retry attempts for transient open failures (SqlException); null/0 disables retry.</summary>
    public int? MaxOpenRetries { get; set; }
    /// <summary>Delay in milliseconds between retries (linear backoff). Default 200ms if retries enabled.</summary>
    public int? RetryDelayMs { get; set; }
    /// <summary>Validate connection on service registration (throws fast if unreachable).</summary>
    public bool ValidateOnBuild { get; set; } = false;
    public JsonSerializerOptions? JsonSerializerOptions { get; set; }
    public bool EnableDiagnostics { get; set; } = true;
}
