/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-14 14:39:27Z</remarks>
namespace RestApi.SpocR;

using System;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

public static class SpocRDbContextServiceCollectionExtensions
{
    /// <summary>Register generated SpocRDbContext and its options.
    /// Connection string precedence:
    /// 1) options.ConnectionString (delegate provided)
    /// 2) IConfiguration.GetConnectionString("DefaultConnection")
    /// </summary>
    public static IServiceCollection AddSpocRDbContext(this IServiceCollection services, Action<SpocRDbContextOptions>? configure = null)
    {
        var explicitOptions = new SpocRDbContextOptions();
        configure?.Invoke(explicitOptions);

        services.AddSingleton(provider =>
        {
            var cfg = provider.GetService<IConfiguration>();
            var name = explicitOptions.ConnectionStringName ?? "DefaultConnection";
            var conn = explicitOptions.ConnectionString ?? cfg?.GetConnectionString(name);
            if (string.IsNullOrWhiteSpace(conn))
                throw new InvalidOperationException($"No connection string resolved for SpocRDbContext (options / IConfiguration:GetConnectionString('{name}')).");
            explicitOptions.ConnectionString = conn;
            if (explicitOptions.CommandTimeoutSeconds is null or <= 0) explicitOptions.CommandTimeoutSeconds = 30;
            if (explicitOptions.MaxOpenRetries is not null and < 0)
                throw new InvalidOperationException("MaxOpenRetries must be >= 0");
            if (explicitOptions.RetryDelayMs is not null and <= 0)
                throw new InvalidOperationException("RetryDelayMs must be > 0");
            if (explicitOptions.ValidateOnBuild)
            {
                try
                {
                    using var probe = new Microsoft.Data.SqlClient.SqlConnection(conn);
                    probe.Open();
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("SpocRDbContext ValidateOnBuild failed to open connection", ex);
                }
            }
            return explicitOptions;
        });

        services.AddScoped<ISpocRDbContext>(sp => new SpocRDbContext(sp.GetRequiredService<SpocRDbContextOptions>()));
        return services;
    }
}
