/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-14 11:54:01Z</remarks>
/// <summary>Generated minimal API endpoints for SpocRDbContext.</summary>
namespace RestApi.SpocR;

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using System.Threading;
using System.Threading.Tasks;

public static class SpocRDbContextEndpointRouteBuilderExtensions
{
    /// <summary>Maps health endpoint for DB connectivity: GET /spocr/health/db (200 ok / 503 problem).</summary>
    public static IEndpointRouteBuilder MapSpocRDbContextEndpoints(this IEndpointRouteBuilder endpoints)
    {
        endpoints.MapGet("/spocr/health/db", async (ISpocRDbContext db, CancellationToken ct) =>
        {
            var healthy = await db.HealthCheckAsync(ct).ConfigureAwait(false);
            return healthy ? Results.Ok(new { status = "ok" }) : Results.Problem("database unavailable", statusCode: 503);
        });
        return endpoints;
    }
}