/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-13 15:36:25Z</remarks>
using System.Text.Json;

namespace RestApi.DataContext.TableTypes
{
    public interface ITableType
    {
    }
}
