/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-13 09:48:53Z</remarks>
using System.Text.Json;

namespace SpocR.Samples.Mssql.DataContext.TableTypes
{
    public interface ITableType
    {
    }
}
