/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-12 23:41:04Z</remarks>
using System;
using System.ComponentModel.DataAnnotations;

namespace SpocR.Samples.Mssql.DataContext.TableTypes.Samples
{
    public class OrderImportTableType : ITableType
    {
        public int? UserId { get; set; }
        public decimal TotalAmount { get; set; }
        public DateTime PlacedAt { get; set; }
    }
}