/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-13 15:36:25Z</remarks>
using System;
using System.ComponentModel.DataAnnotations;

namespace RestApi.DataContext.TableTypes.Samples
{
    public class UserIdListTableType : ITableType
    {
        public int? UserId { get; set; }
    }
}