/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-13 15:36:25Z</remarks>
using System;
using System.ComponentModel.DataAnnotations;

namespace RestApi.DataContext.TableTypes.Samples
{
    public class UserContactTableType : ITableType
    {
        public int? UserId { get; set; }

        [MaxLength(256)]
        public string Email { get; set; }

        [MaxLength(128)]
        public string DisplayName { get; set; }
    }
}