/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 21:06:45Z</remarks>
namespace SpocR.Samples.WebApi.DataContext.DataContext.TableTypes.Samples;
public class OrderImportTableType
{ // modern stub
    public decimal TotalAmount { get; set; }
    public DateTime PlacedAt { get; set; }
// TODO: Replace with modern template content
}