/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 21:06:45Z</remarks>
namespace SpocR.Samples.WebApi.DataContext.DataContext.TableTypes.Samples;
public class UserContactTableType
{ // modern stub
    [MaxLength(256)]
    public string Email { get; set; }

    [MaxLength(128)]
    public string DisplayName { get; set; }
// TODO: Replace with modern template content
}