/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-09 13:57:00Z</remarks>
namespace SpocR.Samples.WebApi.DataContext.TableTypes.Samples;
public record UserIdListTableType(
    int? UserId
) : ITableType;
