/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-09 11:54:40Z</remarks>
namespace SpocR.Samples.WebApi.DataContext.TableTypes.Samples;
public record UserContactTableType(
    int? UserId,
    [property: MaxLength(256)] string Email,
    [property: MaxLength(128)] string DisplayName
) : ITableType;
