using System;

namespace RestApi.DataContext.Models.Samples;
/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-17 10:43:16Z</remarks>
public class SumWithOutput
{
    public int? Result { get; set; }
}