using System;

namespace SpocR.Samples.Mssql.DataContext.Models.Samples;
/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-13 09:48:53Z</remarks>
public class UserBioUpdate
{
    public int UserId { get; set; }
    public string Bio { get; set; }
}