using System;

namespace SpocR.Samples.Mssql.DataContext.Models.Samples;
/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-13 09:48:53Z</remarks>
public class UserFind
{
    public int UserId { get; set; }
    public string Email { get; set; }
    public string DisplayName { get; set; }
    public DateTime CreatedAt { get; set; }
    public string Bio { get; set; }
}