// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace RestApi.SpocR.Samples;

using RestApi.SpocR;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

public readonly record struct CreateUserWithOutputInput(
    string DisplayName,
    string Email
);

public readonly record struct CreateUserWithOutputOutput(
    int? UserId
);

public readonly record struct CreateUserWithOutputResultSet1Result(
    string CreatedUserId
);

public sealed class CreateUserWithOutputResult
{
	public bool Success { get; init; }
	public string? Error { get; init; }
	public CreateUserWithOutputOutput? Output { get; init; }
	public IReadOnlyList<CreateUserWithOutputResultSet1Result> Result { get; init; } = Array.Empty<CreateUserWithOutputResultSet1Result>();
	
}

internal static partial class CreateUserWithOutputPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{

	var parameters = new ProcedureParameter[]
	{
            new("@DisplayName", System.Data.DbType.String, 128, false, false),
            new("@Email", System.Data.DbType.String, 256, false, false),
            new("@UserId", System.Data.DbType.Int32, null, true, true),
        };

	var resultSets = new ResultSetMapping[]
	{
            new("ResultSet1", async (r, ct) =>
    {
		var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "CreatedUserId"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new CreateUserWithOutputResultSet1Result(o0 < 0 ? string.Empty : (r.IsDBNull(o0) ? string.Empty : r.GetString(o0)))); } return list;
    }),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new CreateUserWithOutputOutput(values.TryGetValue("UserId", out var v_UserId) ? (int?)v_UserId : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new CreateUserWithOutputResult
			{
				Success = success,
				Error = error,
				Output = (CreateUserWithOutputOutput?)output,
				// ResultSet 0 → Result (robust list/array handling)
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (CreateUserWithOutputResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (CreateUserWithOutputResultSet1Result)o).ToList() : Array.Empty<CreateUserWithOutputResultSet1Result>())
			};
		};
		void Binder(DbCommand cmd, object? state)
		{
            var input = (CreateUserWithOutputInput)state!;
            cmd.Parameters["@DisplayName"].Value = input.DisplayName;
            cmd.Parameters["@Email"].Value = input.Email;

		}
		return new ProcedureExecutionPlan(
			"[samples].[CreateUserWithOutput]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[samples].[CreateUserWithOutput]' via an <see cref="ISpocRDbContext"/>.</summary>
public static class CreateUserWithOutputExtensions
{
	public static async Task<CreateUserWithOutputResult> CreateUserWithOutputAsync(this ISpocRDbContext db, CreateUserWithOutputInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await CreateUserWithOutputProcedure.ExecuteAsync(conn, input, cancellationToken).ConfigureAwait(false);
	}
}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class CreateUserWithOutputProcedure
{
	public const string Name = "[samples].[CreateUserWithOutput]";
	public static Task<CreateUserWithOutputResult> ExecuteAsync(DbConnection connection, CreateUserWithOutputInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<CreateUserWithOutputResult>(connection, CreateUserWithOutputPlan.Instance, input, cancellationToken);
	}
}
