// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.
namespace RestApi.SpocR.Samples;

using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using SpocR.SpocRVNext.Execution;
public static class CreateUserWithOutputProcedure
{
    public const string Name = "samples.CreateUserWithOutput";
    public static Task<CreateUserWithOutputResultAggregate> ExecuteAsync(DbConnection connection, CreateUserWithOutputInput input, CancellationToken cancellationToken = default)
    {
        return ProcedureExecutor.ExecuteAsync<CreateUserWithOutputResultAggregate>(connection, CreateUserWithOutputProcedurePlan.Instance, input, cancellationToken);
    }
}
