// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace RestApi.SpocR.Samples;

using RestApi.SpocR;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

public readonly record struct CreateUserWithOutputInput(
    string DisplayName,
    string Email
);

public readonly record struct CreateUserWithOutputOutput(
    int? UserId
);

public sealed class CreateUserWithOutputResult
{
	public bool Success { get; init; }
	public string? Error { get; init; }
	public CreateUserWithOutputOutput? Output { get; init; }
	
}

internal static partial class CreateUserWithOutputPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{

	var parameters = new ProcedureParameter[]
	{
            new("@DisplayName", System.Data.DbType.String, 128, false, false),
            new("@Email", System.Data.DbType.String, 256, false, false),
            new("@UserId", System.Data.DbType.Int32, 4, true, true),
        };

	var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new CreateUserWithOutputOutput(values.TryGetValue("UserId", out var v_UserId) ? (int?)v_UserId : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new CreateUserWithOutputResult
			{
				Success = success,
				Error = error,
				Output = (CreateUserWithOutputOutput?)output
			};
		};
		void Binder(DbCommand cmd, object? state)
		{
            var input = (CreateUserWithOutputInput)state!;
            cmd.Parameters["@DisplayName"].Value = input.DisplayName;
            cmd.Parameters["@Email"].Value = input.Email;

		}
		return new ProcedureExecutionPlan(
			"[samples].[CreateUserWithOutput]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[samples].[CreateUserWithOutput]' via an <see cref="ISpocRDbContext"/>.</summary>
public static class CreateUserWithOutputExtensions
{
	public static async Task<CreateUserWithOutputResult> CreateUserWithOutputAsync(this ISpocRDbContext db, CreateUserWithOutputInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await CreateUserWithOutputProcedure.ExecuteAsync(conn, input, cancellationToken).ConfigureAwait(false);
	}
}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class CreateUserWithOutputProcedure
{
	public const string Name = "[samples].[CreateUserWithOutput]";
	public static Task<CreateUserWithOutputResult> ExecuteAsync(DbConnection connection, CreateUserWithOutputInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<CreateUserWithOutputResult>(connection, CreateUserWithOutputPlan.Instance, input, cancellationToken);
	}
}
