// <auto-generated/> Generated by SpocR vNext TableTypesGenerator
namespace RestApi.SpocR.samples;

/// <summary>
/// User Defined Table Type samples.OrderImportTableTypeTableType
/// <remarks>Generated at 2025-10-14T13:14:58.8627603Z</remarks>
/// </summary>
public readonly record struct OrderImportTableTypeTableType(
    int? UserId,
    decimal TotalAmount,
    DateTime PlacedAt
) : ITableType;
