// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.
namespace RestApi.SpocR.Samples;

public readonly record struct OrderListByUserAsJsonResultSet1Row(
    int UserId,
    string DisplayName,
    string Email,
    int OrderId,
    decimal TotalAmount,
    DateTime PlacedAt,
    string Notes
);
