// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace RestApi.SpocR.Samples;

using RestApi.SpocR;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

public readonly record struct OrderListByUserAsJsonInput(
    int? UserId
);

public sealed class OrderListByUserAsJsonResult
{
	public bool Success { get; init; }
	public string? Error { get; init; }
	
}

internal static partial class OrderListByUserAsJsonPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{

	var parameters = new ProcedureParameter[]
	{
            new("@UserId", System.Data.DbType.Int32, null, false, true),
        };

	var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new OrderListByUserAsJsonResult
			{
				Success = success,
				Error = error
			};
		};
		void Binder(DbCommand cmd, object? state)
		{
            var input = (OrderListByUserAsJsonInput)state!;
            cmd.Parameters["@UserId"].Value = input.UserId;

		}
		return new ProcedureExecutionPlan(
			"[samples].[OrderListByUserAsJson]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[samples].[OrderListByUserAsJson]' via an <see cref="ISpocRDbContext"/>.</summary>
public static class OrderListByUserAsJsonExtensions
{
	public static async Task<OrderListByUserAsJsonResult> OrderListByUserAsJsonAsync(this ISpocRDbContext db, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await OrderListByUserAsJsonProcedure.ExecuteAsync(conn, input, cancellationToken).ConfigureAwait(false);
	}
}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class OrderListByUserAsJsonProcedure
{
	public const string Name = "[samples].[OrderListByUserAsJson]";
	public static Task<OrderListByUserAsJsonResult> ExecuteAsync(DbConnection connection, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<OrderListByUserAsJsonResult>(connection, OrderListByUserAsJsonPlan.Instance, input, cancellationToken);
	}
}
