// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.
namespace RestApi.SpocR.Samples;

using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using SpocR.SpocRVNext.Execution;
public static class OrderListAsJsonProcedure
{
    public const string Name = "samples.OrderListAsJson";
    public static Task<OrderListAsJsonResultAggregate> ExecuteAsync(DbConnection connection, CancellationToken cancellationToken = default)
    {
        return ProcedureExecutor.ExecuteAsync<OrderListAsJsonResultAggregate>(connection, OrderListAsJsonProcedurePlan.Instance, null, cancellationToken);
    }
}
