// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.
namespace RestApi.SpocR.Samples;

using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using SpocR.SpocRVNext.Execution;
public static class OrderListByUserAsJsonProcedure
{
    public const string Name = "samples.OrderListByUserAsJson";
    public static Task<OrderListByUserAsJsonResultAggregate> ExecuteAsync(DbConnection connection, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
    {
        return ProcedureExecutor.ExecuteAsync<OrderListByUserAsJsonResultAggregate>(connection, OrderListByUserAsJsonProcedurePlan.Instance, input, cancellationToken);
    }
}
