// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace RestApi.SpocR.Samples;

using RestApi.SpocR;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

public readonly record struct OrderListByUserAsJsonInput(
    int? UserId
);

public readonly record struct OrderListByUserAsJsonResult(
    int UserId,
    string DisplayName,
    string Email,
    int OrderId,
    string TotalAmount,
    string PlacedAt,
    string Notes
);

public sealed class OrderListByUserAsJsonAggregate
{
	public bool Success { get; init; }
	public string? Error { get; init; }
	public IReadOnlyList<OrderListByUserAsJsonResult> Result { get; init; } = Array.Empty<OrderListByUserAsJsonResult>();
	
}

internal static partial class OrderListByUserAsJsonPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{

	var parameters = new ProcedureParameter[]
	{
            new("@UserId", System.Data.DbType.Int32, 4, false, true),
        };

	var resultSets = new ResultSetMapping[]
	{
            new("ResultSet1", async (r, ct) =>
    {
		var list = new System.Collections.Generic.List<object>(); { if (await r.ReadAsync(ct).ConfigureAwait(false) && !r.IsDBNull(0)) { var __raw = r.GetString(0); try { var __single = System.Text.Json.JsonSerializer.Deserialize<OrderListByUserAsJsonResult>(__raw, JsonSupport.Options); if (__single != null) list.Add(__single); } catch { } } } return list;
    }),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new OrderListByUserAsJsonAggregate
			{
				Success = success,
				Error = error,
				// ResultSet 0 → Result (robust list/array handling)
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (OrderListByUserAsJsonResult)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (OrderListByUserAsJsonResult)o).ToList() : Array.Empty<OrderListByUserAsJsonResult>())
			};
		};
		void Binder(DbCommand cmd, object? state)
		{
            var input = (OrderListByUserAsJsonInput)state!;
            cmd.Parameters["@UserId"].Value = input.UserId;

		}
		return new ProcedureExecutionPlan(
			"samples.OrderListByUserAsJson", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing 'samples.OrderListByUserAsJson' via an <see cref="ISpocRDbContext"/>.</summary>
public static class OrderListByUserAsJsonExtensions
{
	public static async Task<OrderListByUserAsJsonAggregate> OrderListByUserAsJsonAsync(this ISpocRDbContext db, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await OrderListByUserAsJsonProcedure.ExecuteAsync(conn, input, cancellationToken).ConfigureAwait(false);
	}
}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class OrderListByUserAsJsonProcedure
{
	public const string Name = "samples.OrderListByUserAsJson";
	public static Task<OrderListByUserAsJsonAggregate> ExecuteAsync(DbConnection connection, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<OrderListByUserAsJsonAggregate>(connection, OrderListByUserAsJsonPlan.Instance, input, cancellationToken);
	}
}
