// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

namespace RestApi.SpocR.Samples;

/// <summary>
/// Result model for samples.OrderListByUserAsJson (Success + optional payload)
/// </summary>
public readonly record struct OrderListByUserAsJsonResult(bool Success, string? Error, SamplesOrderListByUserAsJsonResultSet1Row? Value);
