// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

namespace RestApi.SpocR.Samples;

using System;

/// <summary>
/// User Defined Table Type Samples.OrderImportTableType (columns: 3)
/// <remarks>Generated at <generated></remarks>
/// </summary>
public readonly record struct OrderImportTableType(
    int? UserId,
    decimal TotalAmount,
    DateTime PlacedAt
) : ITableType
{
    public static string TableTypeName => "OrderImportTableType";
}
