// <auto-generated/> Generated by SpocR vNext TableTypesGenerator
namespace RestApi.samples;

/// <summary>
/// User Defined Table Type samples.OrderImportTableTypeTableType
/// <remarks>Generated at 2025-10-13T19:39:55.2769121Z</remarks>
/// </summary>
public readonly record struct OrderImportTableTypeTableType(
    int? UserId,
    decimal TotalAmount,
    DateTime PlacedAt
) : ITableType;
