// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

namespace RestApi.SpocR.Samples;

/// <summary>
/// Result model for samples.OrderListAsJson (Success + optional payload)
/// </summary>
public readonly record struct OrderListAsJsonResult(bool Success, string? Error, SamplesOrderListAsJsonResultSet1Row? Value);
