// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.
namespace RestApi.SpocR.Samples;

using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using SpocR.SpocRVNext.Execution;
public static class SumWithOutputProcedure
{
    public const string Name = "samples.SumWithOutput";
    public static Task<SumWithOutputResultAggregate> ExecuteAsync(DbConnection connection, SumWithOutputInput input, CancellationToken cancellationToken = default)
    {
        return ProcedureExecutor.ExecuteAsync<SumWithOutputResultAggregate>(connection, SumWithOutputProcedurePlan.Instance, input, cancellationToken);
    }
}
