// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace TestNs.SpocR.Samples;

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using TestNs.SpocR;

public readonly record struct SumWithOutputInput(
    int? FirstValue,
    int? SecondValue
);

public readonly record struct SumWithOutputOutput(
    int? Total
);

public readonly record struct SumWithOutputResultSet1Result(
    int OperandA,
    int OperandB,
    int Total
);

public sealed class SumWithOutputResult
{
	public bool Success { get; init; }
	public string? Error { get; init; }
	public SumWithOutputOutput? Output { get; init; }
	public IReadOnlyList<SumWithOutputResultSet1Result> Result { get; init; } = Array.Empty<SumWithOutputResultSet1Result>();
	
}

internal static partial class SumWithOutputPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{

	var parameters = new ProcedureParameter[]
	{
            new("@FirstValue", System.Data.DbType.Int32, null, false, true),
            new("@SecondValue", System.Data.DbType.Int32, null, false, true),
            new("@Total", System.Data.DbType.Int32, null, true, true),
        };

	var resultSets = new ResultSetMapping[]
	{
            new("ResultSet1", async (r, ct) =>
    {
		var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "OperandA"); int o1=ReaderUtil.TryGetOrdinal(r, "OperandB"); int o2=ReaderUtil.TryGetOrdinal(r, "Total"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new SumWithOutputResultSet1Result(o0 < 0 ? default(int) : r.GetInt32(o0), o1 < 0 ? default(int) : r.GetInt32(o1), o2 < 0 ? default(int) : r.GetInt32(o2))); } return list;
    }),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new SumWithOutputOutput(values.TryGetValue("Total", out var v_Total) ? (int?)v_Total : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new SumWithOutputResult
			{
				Success = success,
				Error = error,
				Output = (SumWithOutputOutput?)output,
				// ResultSet 0 → Result (robust list/array handling)
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (SumWithOutputResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (SumWithOutputResultSet1Result)o).ToList() : Array.Empty<SumWithOutputResultSet1Result>())
			};
		};
		void Binder(DbCommand cmd, object? state)
		{
            var input = (SumWithOutputInput)state!;
            cmd.Parameters["@FirstValue"].Value = input.FirstValue;
            cmd.Parameters["@SecondValue"].Value = input.SecondValue;

		}
		return new ProcedureExecutionPlan(
			"[samples].[SumWithOutput]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[samples].[SumWithOutput]' via an <see cref="ISpocRDbContext"/>.</summary>
public static class SumWithOutputExtensions
{
	public static async Task<SumWithOutputResult> SumWithOutputAsync(this ISpocRDbContext db, SumWithOutputInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await SumWithOutputProcedure.ExecuteAsync(conn, input, cancellationToken).ConfigureAwait(false);
	}
}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class SumWithOutputProcedure
{
	public const string Name = "[samples].[SumWithOutput]";
	public static Task<SumWithOutputResult> ExecuteAsync(DbConnection connection, SumWithOutputInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<SumWithOutputResult>(connection, SumWithOutputPlan.Instance, input, cancellationToken);
	}
}
