// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.
namespace RestApi.SpocR.Samples;

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using SpocR.SpocRVNext.Execution;
internal static partial class SumWithOutputProcedurePlan
{
    private static SpocR.SpocRVNext.Execution.ProcedureExecutionPlan? _cached;
    public static SpocR.SpocRVNext.Execution.ProcedureExecutionPlan Instance => _cached ??= Create();
    private static SpocR.SpocRVNext.Execution.ProcedureExecutionPlan Create()
    {
        var parameters = new SpocR.SpocRVNext.Execution.ProcedureParameter[] {
            new("@A", System.Data.DbType.Int32, 4, false, true),
            new("@B", System.Data.DbType.Int32, 4, false, true),
            new("@Sum", System.Data.DbType.Int32, 4, true, true),
            new("@Success", System.Data.DbType.Boolean, 1, true, true),
        };

        var resultSets = new SpocR.SpocRVNext.Execution.ResultSetMapping[] {
            new("ResultSet1", async (r, ct) => { var list = new System.Collections.Generic.List<object>(); int o0=r.GetOrdinal("Result"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new SumWithOutputResultSet1Row(r.IsDBNull(o0) ? null : (int?)r.GetInt32(o0))); } return list; }),
        };

        object? OutputFactory(System.Collections.Generic.IReadOnlyDictionary<string, object?> values) => new SumWithOutputOutput(values.TryGetValue("Sum", out var v_Sum) ? (int?)v_Sum : default, values.TryGetValue("Success", out var v_Success) ? (bool?)v_Success : default);
        object AggregateFactory(bool success, string? error, object? output, System.Collections.Generic.IReadOnlyDictionary<string, object?> outputs, object[] rs) => new SumWithOutputResultAggregate { Success = success, Error = error, Output = (SumWithOutputOutput?)output, ResultSet1 = rs.Length > 0 ? System.Array.ConvertAll(rs[0].ToArray(), o => (SumWithOutputResultSet1Row)o).ToList() : System.Array.Empty<SumWithOutputResultSet1Row>() };

        void Binder(DbCommand cmd, object? state) { var input = (SumWithOutputInput)state!; 
            cmd.Parameters["@A"].Value = input.A;
            cmd.Parameters["@B"].Value = input.B;
        }
        return new SpocR.SpocRVNext.Execution.ProcedureExecutionPlan(
            "samples.SumWithOutput", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
    }
}
