// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.
namespace RestApi.SpocR.Samples;

public sealed class SumWithOutputResultAggregate
{
    public bool Success { get; init; }
    public string? Error { get; init; }
    public SumWithOutputOutput? Output { get; init; }
    public System.Collections.Generic.IReadOnlyList<SumWithOutputResultSet1Row> ResultSet1 { get; init; } = System.Array.Empty<SumWithOutputResultSet1Row>();
}
