// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

namespace RestApi.SpocR.Samples;

/// <summary>
/// Output model for SumWithOutput (2 fields)
/// </summary>
public readonly record struct SumWithOutputOutput(
    int? Sum,
    bool? Success
);
