// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace RestApi.SpocR.Samples;

using RestApi.SpocR;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

public readonly record struct UserDetailsWithOrdersInput(
    int? UserId
);

public sealed class UserDetailsWithOrdersResult
{
	public bool Success { get; init; }
	public string? Error { get; init; }
	
}

internal static partial class UserDetailsWithOrdersPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{

	var parameters = new ProcedureParameter[]
	{
            new("@UserId", System.Data.DbType.Int32, null, false, true),
        };

	var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new UserDetailsWithOrdersResult
			{
				Success = success,
				Error = error
			};
		};
		void Binder(DbCommand cmd, object? state)
		{
            var input = (UserDetailsWithOrdersInput)state!;
            cmd.Parameters["@UserId"].Value = input.UserId;

		}
		return new ProcedureExecutionPlan(
			"[samples].[UserDetailsWithOrders]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[samples].[UserDetailsWithOrders]' via an <see cref="ISpocRDbContext"/>.</summary>
public static class UserDetailsWithOrdersExtensions
{
	public static async Task<UserDetailsWithOrdersResult> UserDetailsWithOrdersAsync(this ISpocRDbContext db, UserDetailsWithOrdersInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await UserDetailsWithOrdersProcedure.ExecuteAsync(conn, input, cancellationToken).ConfigureAwait(false);
	}
}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class UserDetailsWithOrdersProcedure
{
	public const string Name = "[samples].[UserDetailsWithOrders]";
	public static Task<UserDetailsWithOrdersResult> ExecuteAsync(DbConnection connection, UserDetailsWithOrdersInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<UserDetailsWithOrdersResult>(connection, UserDetailsWithOrdersPlan.Instance, input, cancellationToken);
	}
}
