// <auto-generated/> Generated by SpocR vNext TableTypesGenerator
namespace RestApi.SpocR.samples;

/// <summary>
/// User Defined Table Type samples.UserIdListTableTypeTableType
/// <remarks>Generated at 2025-10-14T23:29:50.3485860Z</remarks>
/// </summary>
public readonly record struct UserIdListTableTypeTableType(
    int? UserId
) : ITableType;
