// <auto-generated/> Generated by SpocR vNext TableTypesGenerator
namespace RestApi.samples;

/// <summary>
/// User Defined Table Type samples.UserIdListTableTypeTableType
/// <remarks>Generated at 2025-10-13T16:43:04.5062902Z</remarks>
/// </summary>
public readonly record struct UserIdListTableTypeTableType(
    int? UserId
) : ITableType;
