// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace TestNs.SpocR.Samples;

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using TestNs.SpocR;

public readonly record struct UserBioUpdateInput(
    int? UserId,
    string Bio
);

public sealed class UserBioUpdateResult
{
	public bool Success { get; init; }
	public string? Error { get; init; }
	
}

internal static partial class UserBioUpdatePlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{

	var parameters = new ProcedureParameter[]
	{
            new("@UserId", System.Data.DbType.Int32, null, false, true),
            new("@Bio", System.Data.DbType.String, 512, false, false),
        };

	var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new UserBioUpdateResult
			{
				Success = success,
				Error = error
			};
		};
		void Binder(DbCommand cmd, object? state)
		{
            var input = (UserBioUpdateInput)state!;
            cmd.Parameters["@UserId"].Value = input.UserId;
            cmd.Parameters["@Bio"].Value = input.Bio;

		}
		return new ProcedureExecutionPlan(
			"[samples].[UserBioUpdate]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[samples].[UserBioUpdate]' via an <see cref="ISpocRDbContext"/>.</summary>
public static class UserBioUpdateExtensions
{
	public static async Task<UserBioUpdateResult> UserBioUpdateAsync(this ISpocRDbContext db, UserBioUpdateInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await UserBioUpdateProcedure.ExecuteAsync(conn, input, cancellationToken).ConfigureAwait(false);
	}
}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class UserBioUpdateProcedure
{
	public const string Name = "[samples].[UserBioUpdate]";
	public static Task<UserBioUpdateResult> ExecuteAsync(DbConnection connection, UserBioUpdateInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<UserBioUpdateResult>(connection, UserBioUpdatePlan.Instance, input, cancellationToken);
	}
}
