// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.
namespace RestApi.SpocR.Samples;

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using SpocR.SpocRVNext.Execution;
internal static partial class UserContactSyncProcedurePlan
{
    private static SpocR.SpocRVNext.Execution.ProcedureExecutionPlan? _cached;
    public static SpocR.SpocRVNext.Execution.ProcedureExecutionPlan Instance => _cached ??= Create();
    private static SpocR.SpocRVNext.Execution.ProcedureExecutionPlan Create()
    {
        var parameters = new SpocR.SpocRVNext.Execution.ProcedureParameter[] {
            new("@Contacts", null, null, false, false),
        };

        var resultSets = new SpocR.SpocRVNext.Execution.ResultSetMapping[] {
            new("ResultSet1", async (r, ct) => { var list = new System.Collections.Generic.List<object>(); int o0=r.GetOrdinal("UpdatedContacts"); int o1=r.GetOrdinal("MissingContacts"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new UserContactSyncResultSet1Row(r.IsDBNull(o0) ? null : (int?)r.GetInt32(o0), r.IsDBNull(o1) ? null : (int?)r.GetInt32(o1))); } return list; }),
        };

        object? OutputFactory(System.Collections.Generic.IReadOnlyDictionary<string, object?> values) => null;
        object AggregateFactory(bool success, string? error, object? output, System.Collections.Generic.IReadOnlyDictionary<string, object?> outputs, object[] rs) => new UserContactSyncResultAggregate { Success = success, Error = error, ResultSet1 = rs.Length > 0 ? System.Array.ConvertAll(rs[0].ToArray(), o => (UserContactSyncResultSet1Row)o).ToList() : System.Array.Empty<UserContactSyncResultSet1Row>() };

        void Binder(DbCommand cmd, object? state) { var input = (UserContactSyncInput)state!; 
            cmd.Parameters["@Contacts"].Value = input.Contacts;
        }
        return new SpocR.SpocRVNext.Execution.ProcedureExecutionPlan(
            "samples.UserContactSync", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
    }
}
