// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace RestApi.SpocR.Samples;

using RestApi.SpocR;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

public readonly record struct UserContactSyncInput(
    UserContactTableType Contacts
);

public readonly record struct UserContactSyncResult(
    int? UpdatedContacts,
    int? MissingContacts
);

public sealed class UserContactSyncAggregate
{
	public bool Success { get; init; }
	public string? Error { get; init; }
	public IReadOnlyList<UserContactSyncResult> Result { get; init; } = Array.Empty<UserContactSyncResult>();
	
}

internal static partial class UserContactSyncPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{

	var parameters = new ProcedureParameter[]
	{
            new("@Contacts", System.Data.DbType.Object, null, false, false),
        };

	var resultSets = new ResultSetMapping[]
	{
            new("ResultSet1", async (r, ct) =>
    {
		var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "UpdatedContacts"); int o1=ReaderUtil.TryGetOrdinal(r, "MissingContacts"); if (System.Environment.GetEnvironmentVariable("SPOCR_DUMP_FIRST_ROW") == "1") ReaderUtil.DumpFirstRow(r); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new UserContactSyncResult(o0 < 0 ? null : (r.IsDBNull(o0) ? null : (int?)r.GetInt32(o0)), o1 < 0 ? null : (r.IsDBNull(o1) ? null : (int?)r.GetInt32(o1)))); } return list;
    }),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new UserContactSyncAggregate
			{
				Success = success,
				Error = error,
				// ResultSet 0 → Result (robust list/array handling)
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (UserContactSyncResult)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (UserContactSyncResult)o).ToList() : Array.Empty<UserContactSyncResult>())
			};
		};
		void Binder(DbCommand cmd, object? state)
		{
            var input = (UserContactSyncInput)state!;
            { var prm = cmd.Parameters["@Contacts"]; prm.Value = TvpHelper.BuildRecords(input.Contacts) ?? (object)DBNull.Value; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) sp.SqlDbType = System.Data.SqlDbType.Structured; }

		}
		return new ProcedureExecutionPlan(
			"samples.UserContactSync", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing 'samples.UserContactSync' via an <see cref="ISpocRDbContext"/>.</summary>
public static class UserContactSyncExtensions
{
	public static async Task<UserContactSyncAggregate> UserContactSyncAsync(this ISpocRDbContext db, UserContactSyncInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await UserContactSyncProcedure.ExecuteAsync(conn, input, cancellationToken).ConfigureAwait(false);
	}
}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class UserContactSyncProcedure
{
	public const string Name = "samples.UserContactSync";
	public static Task<UserContactSyncAggregate> ExecuteAsync(DbConnection connection, UserContactSyncInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<UserContactSyncAggregate>(connection, UserContactSyncPlan.Instance, input, cancellationToken);
	}
}
