// <auto-generated/> Generated by SpocR vNext TableTypesGenerator
namespace RestApi.samples;

/// <summary>
/// User Defined Table Type samples.UserIdListTableTypeTableType
/// <remarks>Generated at 2025-10-13T17:23:19.0217146Z</remarks>
/// </summary>
public readonly record struct UserIdListTableTypeTableType(
    int? UserId
) : ITableType;
