// <auto-generated/> Generated by SpocR vNext TableTypesGenerator
namespace RestApi.samples;

/// <summary>
/// User Defined Table Type samples.UserContactTableTypeTableType
/// <remarks>Generated at 2025-10-13T16:43:04.5060100Z</remarks>
/// </summary>
public readonly record struct UserContactTableTypeTableType(
    int? UserId,
    string Email,
    string DisplayName
) : ITableType;
