// <auto-generated/> Generated by SpocR vNext TableTypesGenerator
namespace RestApi.samples;

/// <summary>
/// User Defined Table Type samples.UserIdListTableTypeTableType
/// <remarks>Generated at 2025-10-13T19:39:55.2779766Z</remarks>
/// </summary>
public readonly record struct UserIdListTableTypeTableType(
    int? UserId
) : ITableType;
