// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.
namespace RestApi.SpocR.Samples;

public sealed class UserBioUpdateResultAggregate
{
    public bool Success { get; init; }
    public string? Error { get; init; }
    public System.Collections.Generic.IReadOnlyList<UserBioUpdateResultSet1Row> ResultSet1 { get; init; } = System.Array.Empty<UserBioUpdateResultSet1Row>();
}
