// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.
namespace RestApi.SpocR.Samples;

using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using SpocR.SpocRVNext.Execution;
public static class UserContactSyncProcedure
{
    public const string Name = "samples.UserContactSync";
    public static Task<UserContactSyncResultAggregate> ExecuteAsync(DbConnection connection, UserContactSyncInput input, CancellationToken cancellationToken = default)
    {
        return ProcedureExecutor.ExecuteAsync<UserContactSyncResultAggregate>(connection, UserContactSyncProcedurePlan.Instance, input, cancellationToken);
    }
}
