// <auto-generated/> Generated by SpocR vNext TableTypesGenerator
namespace RestApi.SpocR.samples;

/// <summary>
/// User Defined Table Type samples.UserContactTableTypeTableType
/// <remarks>Generated at 2025-10-14T14:39:27.8932516Z</remarks>
/// </summary>
public readonly record struct UserContactTableTypeTableType(
    int? UserId,
    string Email,
    string DisplayName
) : ITableType;
