// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

namespace RestApi.SpocR.Samples;

/// <summary>
/// Input model for UserContactSync (1 parameters)
/// </summary>
public readonly record struct UserContactSyncInput(
    string Contacts
);
