// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
namespace RestApi.SpocR.Samples;

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using RestApi.SpocR;

public readonly record struct UserDetailsWithOrdersInput(
    int? UserId
);



public readonly record struct UserDetailsWithOrdersResultSet1Result(
    int UserId,
    string DisplayName,
    string Email,
    DateTime CreatedAt,
    string Bio
);

public sealed class UserDetailsWithOrdersResult
{
    public bool Success { get; init; }
    public string? Error { get; init; }
    public IReadOnlyList<UserDetailsWithOrdersResultSet1Result> Result1 { get; init; } = Array.Empty<UserDetailsWithOrdersResultSet1Result>();
}

internal static partial class UserDetailsWithOrdersProcedurePlan
{
    private static ProcedureExecutionPlan? _cached;
    public static ProcedureExecutionPlan Instance => _cached ??= Create();
    private static ProcedureExecutionPlan Create()
    {
        var parameters = new ProcedureParameter[] {
            new("@UserId", System.Data.DbType.Int32, 4, false, true),
        };

        var resultSets = new ResultSetMapping[] {
            new("ResultSet1", async (r, ct) => { var list = new List<object>(); int o0=r.GetOrdinal("UserId"); int o1=r.GetOrdinal("DisplayName"); int o2=r.GetOrdinal("Email"); int o3=r.GetOrdinal("CreatedAt"); int o4=r.GetOrdinal("Bio"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new UserDetailsWithOrdersResultSet1Result(r.GetInt32(o0), r.IsDBNull(o1) ? string.Empty : r.GetString(o1), r.IsDBNull(o2) ? string.Empty : r.GetString(o2), r.GetDateTime(o3), r.IsDBNull(o4) ? string.Empty : r.GetString(o4))); } return list; }),
        };

        object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
        object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs) => new UserDetailsWithOrdersResult { Success = success, Error = error, Result1 = rs.Length > 0 ? Array.ConvertAll(((System.Collections.Generic.List<object>)rs[0]).ToArray(), o => (UserDetailsWithOrdersResultSet1Result)o).ToList() : Array.Empty<UserDetailsWithOrdersResultSet1Result>() };
        void Binder(DbCommand cmd, object? state) { var input = (UserDetailsWithOrdersInput)state!; 
            cmd.Parameters["@UserId"].Value = input.UserId;
        }
        return new ProcedureExecutionPlan(
            "samples.UserDetailsWithOrders", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
    }
}

public static class UserDetailsWithOrdersProcedure
{
    public const string Name = "samples.UserDetailsWithOrders";
    public static Task<UserDetailsWithOrdersResult> ExecuteAsync(DbConnection connection, UserDetailsWithOrdersInput input, CancellationToken cancellationToken = default)
    {
        return ProcedureExecutor.ExecuteAsync<UserDetailsWithOrdersResult>(connection, UserDetailsWithOrdersProcedurePlan.Instance, input, cancellationToken);
    }
}
