// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.
namespace RestApi.SpocR.Samples;

using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using SpocR.SpocRVNext.Execution;
public static class UserDetailsWithOrdersProcedure
{
    public const string Name = "samples.UserDetailsWithOrders";
    public static Task<UserDetailsWithOrdersResultAggregate> ExecuteAsync(DbConnection connection, UserDetailsWithOrdersInput input, CancellationToken cancellationToken = default)
    {
        return ProcedureExecutor.ExecuteAsync<UserDetailsWithOrdersResultAggregate>(connection, UserDetailsWithOrdersProcedurePlan.Instance, input, cancellationToken);
    }
}
