// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.
namespace RestApi.SpocR.Samples;

public readonly record struct UserListResultSet1Row(
    int UserId,
    string Email,
    string DisplayName,
    DateTime CreatedAt,
    string Bio
);
