// <auto-generated/>
// SpocR v4.5 Bridge Phase (vNext generator). Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.
namespace RestApi.SpocR.Samples;

using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using SpocR.SpocRVNext.Execution;
public static class UserBioUpdateProcedure
{
    public const string Name = "samples.UserBioUpdate";
    public static Task<UserBioUpdateResultAggregate> ExecuteAsync(DbConnection connection, UserBioUpdateInput input, CancellationToken cancellationToken = default)
    {
        return ProcedureExecutor.ExecuteAsync<UserBioUpdateResultAggregate>(connection, UserBioUpdateProcedurePlan.Instance, input, cancellationToken);
    }
}
