/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:31:25Z</remarks>
namespace SpocR.Samples.WebApi.SpocR;

public class SpocRStoredProcedureCallOptions{ public int? CommandTimeout { get; set; } public ISpocRTransaction Transaction { get; set; } }
public partial class SpocRDbContext { /* partial methods generated per stored procedure file */ }
