/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-09 13:57:00Z</remarks>
using System;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using System.Threading;
using System.Threading.Tasks;
using SpocR.Samples.WebApi.DataContext.Models;
using SpocR.Samples.WebApi.DataContext.Outputs;
using SpocR.Samples.WebApi.DataContext;
using SpocR.Samples.WebApi.DataContext.DataContext.Inputs.Samples;
using SpocR.Samples.WebApi.DataContext.DataContext.Outputs;
using SpocR.Samples.WebApi.DataContext.DataContext.Outputs.Samples;

namespace SpocR.Samples.WebApi.DataContext.StoredProcedures.Samples;
public static class CreateUserWithOutputExtensions
{
    public static Task<int?> CreateUserWithOutputAsync(this IAppDbContextPipe context, CreateUserWithOutputInput input, CancellationToken cancellationToken)
    {
        if (context == null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        var parameters = new List<SqlParameter>
        {
            AppDbContext.GetParameter("DisplayName", input.DisplayName, false, 128),
            AppDbContext.GetParameter("Email", input.Email, false, 256),
            AppDbContext.GetParameter("UserId", input.UserId, true, 4)
        };
        return context.ExecuteScalarAsync<int?>("[samples].[CreateUserWithOutput]", parameters, cancellationToken);
    }

    public static Task<int?> CreateUserWithOutputAsync(this IAppDbContext context, CreateUserWithOutputInput input, CancellationToken cancellationToken)
    {
        return context.CreatePipe().CreateUserWithOutputAsync(input, cancellationToken);
    }
}