/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:38:31Z</remarks>
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
namespace SpocR.Samples.WebApi.DataContext.StoredProcedures.Samples;

public static class CreateUserWithOutputExtensions
{
    /// <summary>Executes [samples].[CreateUserWithOutput] and returns CrudResult.</summary>
    public static Task<CrudResult> CreateUserWithOutputAsync(this IAppDbContextPipe context, CreateUserWithOutputInput input, CancellationToken cancellationToken = default)
    {
        if(context==null) throw new ArgumentNullException("context");
        var parameters = new List<SqlParameter>()
        {
            new SqlParameter("@DisplayName", (object)input.DisplayName ?? DBNull.Value) { SqlDbType = System.Data.SqlDbType.NVarChar, Size = 128, Direction = ParameterDirection.Input },
            new SqlParameter("@Email", (object)input.Email ?? DBNull.Value) { SqlDbType = System.Data.SqlDbType.NVarChar, Size = 256, Direction = ParameterDirection.Input },
            new SqlParameter("@UserId", DBNull.Value) { SqlDbType = System.Data.SqlDbType.Int, Direction = ParameterDirection.Output }
        };
        return context.ExecuteSingleAsync<CrudResult>("[samples].[CreateUserWithOutput]", parameters, cancellationToken);
    }

}
