/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:38:31Z</remarks>
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
namespace SpocR.Samples.WebApi.DataContext.StoredProcedures.Samples;

public static class OrderListByUserAsJsonExtensions
{
    /// <summary>Executes [samples].[OrderListByUserAsJson] and returns the raw JSON string.</summary>
    public static Task<string> OrderListByUserAsJsonAsync(this IAppDbContextPipe context, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
    {
        if(context==null) throw new ArgumentNullException("context");
        var parameters = new List<SqlParameter>()
        {
            new SqlParameter("@UserId", (object)input.UserId ?? DBNull.Value) { SqlDbType = System.Data.SqlDbType.Int, Direction = ParameterDirection.Input }
        };
        return context.ReadJsonAsync("[samples].[OrderListByUserAsJson]", parameters, cancellationToken);
    }

    /// <summary>Executes [samples].[OrderListByUserAsJson] and deserializes the JSON response to OrderListByUserAsJson.</summary>
    public static async Task<OrderListByUserAsJson> OrderListByUserAsJsonDeserializeAsync(this IAppDbContextPipe context, OrderListByUserAsJsonInput input, CancellationToken cancellationToken = default)
    {
        if(context==null) throw new ArgumentNullException("context");
        var parameters = new List<SqlParameter>()
        {
            new SqlParameter("@UserId", (object)input.UserId ?? DBNull.Value) { SqlDbType = System.Data.SqlDbType.Int, Direction = ParameterDirection.Input }
        };
        return await context.ReadJsonDeserializeAsync<OrderListByUserAsJson>("[samples].[OrderListByUserAsJson]", parameters, cancellationToken);
    }

}
