/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:38:31Z</remarks>
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
namespace SpocR.Samples.WebApi.DataContext.StoredProcedures.Samples;

public static class OrderListAsJsonExtensions
{
    /// <summary>Executes [samples].[OrderListAsJson] and returns the raw JSON string.</summary>
    public static Task<string> OrderListAsJsonAsync(this IAppDbContextPipe context, CancellationToken cancellationToken = default)
    {
        if(context==null) throw new ArgumentNullException("context");
        var parameters = new List<SqlParameter>()
        {

        };
        return context.ReadJsonAsync("[samples].[OrderListAsJson]", parameters, cancellationToken);
    }

    /// <summary>Executes [samples].[OrderListAsJson] and deserializes the JSON response to List<OrderListAsJson>.</summary>
    public static async Task<List<OrderListAsJson>> OrderListAsJsonDeserializeAsync(this IAppDbContextPipe context, CancellationToken cancellationToken = default)
    {
        if(context==null) throw new ArgumentNullException("context");
        var parameters = new List<SqlParameter>()
        {

        };
        return await context.ReadJsonDeserializeAsync<List<OrderListAsJson>>("[samples].[OrderListAsJson]", parameters, cancellationToken);
    }

}
