/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:38:31Z</remarks>
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
namespace SpocR.Samples.WebApi.DataContext.StoredProcedures.Samples;

public static class SumWithOutputExtensions
{
    /// <summary>Executes [samples].[SumWithOutput] and returns CrudResult.</summary>
    public static Task<CrudResult> SumWithOutputAsync(this IAppDbContextPipe context, SumWithOutputInput input, CancellationToken cancellationToken = default)
    {
        if(context==null) throw new ArgumentNullException("context");
        var parameters = new List<SqlParameter>()
        {
            new SqlParameter("@A", (object)input.A ?? DBNull.Value) { SqlDbType = System.Data.SqlDbType.Int, Direction = ParameterDirection.Input },
            new SqlParameter("@B", (object)input.B ?? DBNull.Value) { SqlDbType = System.Data.SqlDbType.Int, Direction = ParameterDirection.Input },
            new SqlParameter("@Sum", DBNull.Value) { SqlDbType = System.Data.SqlDbType.Int, Direction = ParameterDirection.Output },
            new SqlParameter("@Success", DBNull.Value) { SqlDbType = System.Data.SqlDbType.Bit, Direction = ParameterDirection.Output }
        };
        return context.ExecuteSingleAsync<CrudResult>("[samples].[SumWithOutput]", parameters, cancellationToken);
    }

}
