/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 21:06:45Z</remarks>
using System;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using System.Threading;
using System.Threading.Tasks;
using SpocR.Samples.WebApi.DataContext.DataContext.Models;
using SpocR.Samples.WebApi.DataContext.DataContext.Outputs;
using SpocR.Samples.WebApi.DataContext.DataContext;
using SpocR.Samples.WebApi.DataContext.DataContext.Models.Samples;
using SpocR.Samples.WebApi.DataContext.DataContext.Inputs.Samples;

namespace SpocR.Samples.WebApi.DataContext.DataContext.StoredProcedures.Samples
{
    public static class UserBioUpdateExtensions
    {
        public static Task<UserBioUpdate> UserBioUpdateAsync(this IAppDbContextPipe context, UserBioUpdateInput input, CancellationToken cancellationToken)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            var parameters = new List<SqlParameter>
            {
                AppDbContext.GetParameter("UserId", input.UserId, false, 4),
                AppDbContext.GetParameter("Bio", input.Bio, false, 512)
            };
            return context.ExecuteSingleAsync<UserBioUpdate>("[samples].[UserBioUpdate]", parameters, cancellationToken);
        }

        public static Task<UserBioUpdate> UserBioUpdateAsync(this IAppDbContext context, UserBioUpdateInput input, CancellationToken cancellationToken)
        {
            return context.CreatePipe().UserBioUpdateAsync(input, cancellationToken);
        }
    }
}