/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-09 11:54:40Z</remarks>
using System;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using System.Threading;
using System.Threading.Tasks;
using SpocR.Samples.WebApi.DataContext.Models;
using SpocR.Samples.WebApi.DataContext.Outputs;
using SpocR.Samples.WebApi.DataContext;
using SpocR.Samples.WebApi.DataContext.DataContext.Models.Samples;
using SpocR.Samples.WebApi.DataContext.DataContext.Inputs.Samples;

namespace SpocR.Samples.WebApi.DataContext.StoredProcedures.Samples;
public static class UserFindExtensions
{
    public static Task<UserFind> UserFindAsync(this IAppDbContextPipe context, UserFindInput input, CancellationToken cancellationToken)
    {
        if (context == null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        var parameters = new List<SqlParameter>
        {
            AppDbContext.GetParameter("UserId", input.UserId, false, 4)
        };
        return context.ExecuteSingleAsync<UserFind>("[samples].[UserFind]", parameters, cancellationToken);
    }

    public static Task<UserFind> UserFindAsync(this IAppDbContext context, UserFindInput input, CancellationToken cancellationToken)
    {
        return context.CreatePipe().UserFindAsync(input, cancellationToken);
    }
}