/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:38:31Z</remarks>
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
namespace SpocR.Samples.WebApi.DataContext.StoredProcedures.Samples;

public static class UserContactSyncExtensions
{
    /// <summary>Executes [samples].[UserContactSync] and returns CrudResult.</summary>
    public static Task<CrudResult> UserContactSyncAsync(this IAppDbContextPipe context, UserContactSyncInput input, CancellationToken cancellationToken = default)
    {
        if(context==null) throw new ArgumentNullException("context");
        var parameters = new List<SqlParameter>()
        {
            new SqlParameter("@Contacts", System.Data.SqlDbType.Structured) { TypeName = "samples.UserContactTableType", Direction = ParameterDirection.Input }
        };
        return context.ExecuteSingleAsync<CrudResult>("[samples].[UserContactSync]", parameters, cancellationToken);
    }

}
