/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 21:06:45Z</remarks>
using System;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using System.Threading;
using System.Threading.Tasks;
using SpocR.Samples.WebApi.DataContext.DataContext.Models;
using SpocR.Samples.WebApi.DataContext.DataContext.Outputs;
using SpocR.Samples.WebApi.DataContext.DataContext;
using SpocR.Samples.WebApi.DataContext.DataContext.Models.Samples;

namespace SpocR.Samples.WebApi.DataContext.DataContext.StoredProcedures.Samples
{
    public static class UserListExtensions
    {
        public static Task<List<UserList>> UserListAsync(this IAppDbContextPipe context, CancellationToken cancellationToken)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            var parameters = new List<SqlParameter>
            {
            };
            return context.ExecuteListAsync<UserList>("[samples].[UserList]", parameters, cancellationToken);
        }

        public static Task<List<UserList>> UserListAsync(this IAppDbContext context, CancellationToken cancellationToken)
        {
            return context.CreatePipe().UserListAsync(cancellationToken);
        }
    }
}