/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:38:31Z</remarks>
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
namespace SpocR.Samples.WebApi.DataContext.StoredProcedures.Samples;

public static class UserOrderHierarchyJsonExtensions
{
    /// <summary>Executes [samples].[UserOrderHierarchyJson] and returns the raw JSON string.</summary>
    public static Task<string> UserOrderHierarchyJsonAsync(this IAppDbContextPipe context, CancellationToken cancellationToken = default)
    {
        if(context==null) throw new ArgumentNullException("context");
        var parameters = new List<SqlParameter>()
        {

        };
        return context.ReadJsonAsync("[samples].[UserOrderHierarchyJson]", parameters, cancellationToken);
    }

    /// <summary>Executes [samples].[UserOrderHierarchyJson] and deserializes the JSON response to List<UserOrderHierarchyJson>.</summary>
    public static async Task<List<UserOrderHierarchyJson>> UserOrderHierarchyJsonDeserializeAsync(this IAppDbContextPipe context, CancellationToken cancellationToken = default)
    {
        if(context==null) throw new ArgumentNullException("context");
        var parameters = new List<SqlParameter>()
        {

        };
        return await context.ReadJsonDeserializeAsync<List<UserOrderHierarchyJson>>("[samples].[UserOrderHierarchyJson]", parameters, cancellationToken);
    }

}
