/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 22:44:50Z</remarks>
using System;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using System.Threading;
using System.Threading.Tasks;
using SpocR.Samples.WebApi.DataContext.Models;
using SpocR.Samples.WebApi.DataContext.Outputs;
using SpocR.Samples.WebApi.DataContext;
using SpocR.Samples.WebApi.DataContext.DataContext.Models.Samples;
using SpocR.Samples.WebApi.DataContext.DataContext.Inputs.Samples;
using SpocR.Samples.WebApi.DataContext.DataContext.TableTypes.Samples;

namespace SpocR.Samples.WebApi.DataContext.StoredProcedures.Samples;
public static class UserContactSyncExtensions
{
    public static Task<UserContactSync> UserContactSyncAsync(this IAppDbContextPipe context, UserContactSyncInput input, CancellationToken cancellationToken)
    {
        if (context == null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        var parameters = new List<SqlParameter>
        {
            AppDbContext.GetCollectionParameter("Contacts", input.Contacts)
        };
        return context.ExecuteSingleAsync<UserContactSync>("[samples].[UserContactSync]", parameters, cancellationToken);
    }

    public static Task<UserContactSync> UserContactSyncAsync(this IAppDbContext context, UserContactSyncInput input, CancellationToken cancellationToken)
    {
        return context.CreatePipe().UserContactSyncAsync(input, cancellationToken);
    }
}