/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:38:31Z</remarks>
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
namespace SpocR.Samples.WebApi.DataContext.StoredProcedures.Samples;

public static class UserListExtensions
{
    /// <summary>Executes [samples].[UserList] and returns CrudResult.</summary>
    public static Task<CrudResult> UserListAsync(this IAppDbContextPipe context, CancellationToken cancellationToken = default)
    {
        if(context==null) throw new ArgumentNullException("context");
        var parameters = new List<SqlParameter>()
        {

        };
        return context.ExecuteSingleAsync<CrudResult>("[samples].[UserList]", parameters, cancellationToken);
    }

}
