/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 22:44:50Z</remarks>
namespace SpocR.Samples.WebApi.DataContext.Outputs.Samples;
/// <summary>Auto-generated OUTPUT model for stored procedure '[samples].[CreateUserWithOutput]'.</summary>
/// <remarks>Generated by SpocR – do not edit manually.</remarks>
public class CreateUserWithOutputOutput : Output
{ // modern stub
    public int? UserId { get; set; }
// TODO: Replace with modern template content
}