using System;

namespace spocr.DataContext.Models.Samples
{
    /// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
    /// <remarks>Generated at 2025-10-08 16:15:37Z</remarks>
    public class OrderListByUserAsJson
    {
        public int UserId { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public int OrderId { get; set; }
        public decimal TotalAmount { get; set; }
        public DateTime PlacedAt { get; set; }
        public string Notes { get; set; }
    }
}