namespace SpocR.Samples.WebApi.DataContext.DataContext.Models.Samples;
/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 21:06:45Z</remarks>
public class UserContactSync
{ // modern stub
    public int? MissingContacts { get; set; }
// TODO: Replace with modern template content
}