namespace SpocR.Samples.WebApi.DataContext.Models.Samples;
/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-09 14:49:09Z</remarks>
public class UserDetailsWithOrders
{
    public string DisplayName { get; set; }
    public string Email { get; set; }
    public DateTime CreatedAt { get; set; }
    public string? Bio { get; set; }
}