using System;

namespace SpocR.Samples.WebApi.DataContext.Models.Samples;
/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-11 19:31:25Z</remarks>
public class UserBioUpdate
{
    public int UserId { get; set; }
    public string? Bio { get; set; }
}