namespace SpocR.Samples.WebApi.DataContext.Models.Samples;
/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-09 11:54:40Z</remarks>
public class UserBioUpdate
{
    public string Bio { get; set; }
}