namespace SpocR.Samples.WebApi.DataContext.Models.Samples;
/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-09 11:53:55Z</remarks>
public class UserOrderHierarchyJson
{
    public string DisplayName { get; set; }
    public string Email { get; set; }
    public string Orders { get; set; }
}