namespace SpocR.Samples.WebApi.DataContext.DataContext.Models.Samples;
/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 21:06:45Z</remarks>
public class UserDetailsWithOrders
{ // modern stub
    public string DisplayName { get; set; }
    public string Email { get; set; }
    public DateTime CreatedAt { get; set; }
    public string Bio { get; set; }
// TODO: Replace with modern template content
}