using System;

namespace spocr.DataContext.Models.Samples
{
    /// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
    /// <remarks>Generated at 2025-10-08 16:15:37Z</remarks>
    public class UserBioUpdate
    {
        public int UserId { get; set; }
        public string Bio { get; set; }
    }
}