using System;

namespace spocr.DataContext.Models.Samples
{
    /// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
    /// <remarks>Generated at 2025-10-08 16:15:37Z</remarks>
    public class UserContactSync
    {
        public int? UpdatedContacts { get; set; }
        public int? MissingContacts { get; set; }
    }
}