/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-08 22:44:50Z</remarks>
namespace SpocR.Samples.WebApi.DataContext.Outputs;
public class Outputs
{ // modern stub
// TODO: Replace with modern template content
}