/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-09 15:13:27Z</remarks>
namespace SpocR.Samples.WebApi.DataContext.Outputs;
public class Outputs
{
}