/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-12 23:41:04Z</remarks>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SpocR.Samples.Mssql.DataContext.Outputs.Samples
{
    /// <summary>Auto-generated OUTPUT model for stored procedure '[samples].[CreateUserWithOutput]'.</summary>
    /// <remarks>Generated by SpocR – do not edit manually.</remarks>
    public class CreateUserWithOutputOutput : Output
    {
        public int? UserId { get; set; }
    }
}