using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RestApi.DataContext.Outputs.Samples
{
    /// <summary>Auto-generated OUTPUT model for stored procedure '[samples].[CreateUserWithOutput]'.</summary>
    /// <remarks>Generated by SpocR – do not edit manually.</remarks>
    public class CreateUserWithOutputOutput : Output
    {
        public int? UserId { get; set; }
    }
}