/// <summary>Auto-generated by SpocR. DO NOT EDIT. Changes will be overwritten on rebuild.</summary>
/// <remarks>Generated at 2025-10-13 15:36:25Z</remarks>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RestApi.DataContext.Outputs.Samples
{
    /// <summary>Auto-generated OUTPUT model for stored procedure '[samples].[SumWithOutput]'.</summary>
    /// <remarks>Generated by SpocR – do not edit manually.</remarks>
    public class SumWithOutputOutput : Output
    {
        public int? Sum { get; set; }
        public bool? Success { get; set; }
    }
}