name: Publish NuGet

on:
  release:
    types: [published] # Only a published GitHub Release triggers publish now
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Do not push package (build + pack + summary only)"
        required: false
        default: "true"
        type: choice
        options: ["true", "false"]
      override-version:
        description: "Override version (for workflow_dispatch only, no publish)"
        required: false
        default: ""
        type: string

concurrency:
  group: publish-nuget
  cancel-in-progress: false

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: build, validate, pack & publish
    runs-on: ubuntu-latest
    env:
      PROJECT_FILE: src/SpocR.csproj
      ARTIFACTS_DIR: .artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup .NET 9 (multi-target support)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Show .NET Info
        run: dotnet --info

      - name: Restore
        run: dotnet restore $PROJECT_FILE

      - name: Build (Release)
        run: dotnet build $PROJECT_FILE --configuration Release --no-restore -p:ContinuousIntegrationBuild=true -p:Deterministic=true

      - name: Determine Version (git tags / MinVer compatible)
        id: version
        run: |
          EVENT="${{ github.event_name }}"
          OVERRIDE="${{ inputs.override-version }}"
          if [ "$EVENT" = "release" ]; then
            RAW_TAG="${{ github.event.release.tag_name }}"
            VERSION="${RAW_TAG#v}"
            echo "Release event: using tag $RAW_TAG -> version $VERSION"
          elif [ "$EVENT" = "workflow_dispatch" ] && [ -n "$OVERRIDE" ]; then
            VERSION="$OVERRIDE"
            echo "Dispatch override provided -> version $VERSION"
          else
            # Fallback: derive latest tag (SemVer-style starting with v). If none, use 0.0.0-local
            LATEST_TAG=$(git describe --tags --match "v[0-9]*" --abbrev=0 2>/dev/null || true)
            if [ -z "$LATEST_TAG" ]; then
              VERSION="0.0.0-local"
              echo "No tags found. Using fallback version $VERSION"
            else
              VERSION="${LATEST_TAG#v}"
              echo "Derived version from latest tag $LATEST_TAG -> $VERSION"
            fi
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "base-version=$VERSION" >> $GITHUB_OUTPUT

      - name: Validate Release Tag matches Version
        if: github.event_name == 'release'
        run: |
          TAG="${{ github.event.release.tag_name }}"
          EXPECTED="v${{ steps.version.outputs.version }}"
          echo "Release tag: $TAG / Expected: $EXPECTED"
          if [ "$TAG" != "$EXPECTED" ]; then
            echo "Tag and project version mismatch"; exit 1;
          fi

      - name: Note Dispatch Context
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Manual dispatch detected." 
          echo "Dry-run: ${{ inputs['dry-run'] }}" 
          if [ -n "${{ inputs.override-version }}" ]; then echo "Override version used: ${{ inputs.override-version }}"; fi

      - name: Self-Validation (internal test command)
        run: dotnet run --framework net8.0 --project $PROJECT_FILE --configuration Release -- test --validate

      - name: Run Tests
        run: dotnet test tests/Tests.sln --configuration Release --settings SpocR.runsettings

      - name: Check if Package Already Exists on NuGet
        id: nuget_exists
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          PKG_URL="https://api.nuget.org/v3-flatcontainer/spocr/${VERSION}/spocr.${VERSION}.nupkg"
            echo "Checking $PKG_URL"
          if curl -s --head --fail "$PKG_URL" > /dev/null; then
            echo "already=true" >> $GITHUB_OUTPUT
            echo "Package version already exists on NuGet. Skipping publish."
          else
            echo "already=false" >> $GITHUB_OUTPUT
            echo "Package version not on NuGet. Proceeding."
          fi

      - name: Evaluate Publish Conditions
        id: publish_gate
        run: |
          EVENT="${{ github.event_name }}"
          ALREADY="${{ steps.nuget_exists.outputs.already }}"
          # Only publish when this is a GitHub Release (published) AND not already on NuGet
          if [ "$EVENT" = "release" ] && [ "$ALREADY" != "true" ]; then
            echo "will-publish=true" >> $GITHUB_OUTPUT
            echo "Eligible for publish (GitHub Release event)"
          else
            echo "will-publish=false" >> $GITHUB_OUTPUT
            echo "Skipping publish (event=$EVENT, already=$ALREADY)"
          fi

      - name: Pack
        # Always pack so artifacts are available for inspection even if not publishing
        run: |
          mkdir -p $ARTIFACTS_DIR/nuget
          dotnet pack $PROJECT_FILE \
            --configuration Release \
            --no-build \
            -p:ContinuousIntegrationBuild=true \
            -p:RepositoryUrl=${{ github.server_url }}/${{ github.repository }} \
            -p:RepositoryCommit=${{ github.sha }} \
            -o $ARTIFACTS_DIR/nuget

      - name: Install CycloneDX tool
        run: dotnet tool update --global CycloneDX || dotnet tool install --global CycloneDX

      - name: Ensure CycloneDX on PATH
        run: |
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          echo "Added dotnet tools dir to PATH via GITHUB_PATH"

      - name: Generate SBOM (CycloneDX)
        run: |
          set -euo pipefail
          mkdir -p "$ARTIFACTS_DIR/sbom"
          # Install/Update CycloneDX .NET Tool (command is invoked via 'dotnet CycloneDX')
          dotnet tool update --global CycloneDX || dotnet tool install --global CycloneDX
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          # The global tool exposes the command name 'dotnet-cyclonedx' (invoked as 'dotnet CycloneDX').
          echo "Listing global dotnet tools for diagnostics:" >&2
          dotnet tool list --global >&2 || true
          echo "Running: dotnet CycloneDX dotnet --project-file $PROJECT_FILE --out $ARTIFACTS_DIR/sbom --json" >&2
          dotnet CycloneDX dotnet --project-file "$PROJECT_FILE" --out "$ARTIFACTS_DIR/sbom" --json

      - name: Push to NuGet
        if: steps.publish_gate.outputs.will-publish == 'true'
        run: |
          dotnet nuget push "$ARTIFACTS_DIR/nuget/*.nupkg" \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate

      - name: Upload Artifacts (Package + SBOM)
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package-and-sbom
          path: |
            .artifacts/nuget/*.nupkg
            .artifacts/sbom/*

      - name: Summary
        run: |
          echo "## Publish Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Version: ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.publish_gate.outputs.will-publish }}" = "true" ]; then
            echo "- Status: Published" >> $GITHUB_STEP_SUMMARY
          else
            echo "- Status: Skipped (Dry run / Already published / Override)" >> $GITHUB_STEP_SUMMARY
          fi
